name: Build CutVPN

on:
  workflow_dispatch:
  push:
    paths:
      - 'ui/**'
      - 'installer/**'
      - '.github/workflows/build.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish CutVPN
        run: dotnet publish ui/CutVPN.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Install Inno Setup
        shell: powershell
        run: choco install innosetup --yes --no-progress

      - name: Build CutVPN installer
        shell: powershell
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\CutVPN.iss"

      - name: Upload CutVPN EXE
        uses: actions/upload-artifact@v4
        with:
          name: CutVPN-win-x64
          path: ui/bin/Release/net8.0-windows/win-x64/publish/

      - name: Upload CutVPN installer
        uses: actions/upload-artifact@v4
        with:
          name: CutVPN-Setup
          path: installer/out/CutVPN-Setup.exe
